name: "200lab CD"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  cd:
    name: SSH to server and deploy
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Tags docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: hero2510/crawler-website
          tags: |
            type=raw,value={{date 'YYYY-MM-DD'}}

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIV_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/actions-runner/workingdir/crawler-website/crawler-website
            sh deploy.sh
