name: "200lab CI"

on:
  pull_request:
    branches:
      - "main"
permissions:
  contents: write
  actions: read

jobs:
  ci:
    name: Build and push image to Docker hub
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tags docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: hero2510/crawler-website
          tags: |
            type=raw,value={{date 'YYYY-MM-DD'}}

      - name: Build and push to docker hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
